### PR TITLE
add tests for Thai

### PR DESCRIPTION
**Pull request by prideloki**
I notice that in the full date format, there is an extra space between the month and the year in Thai. for example, https://github.com/go-playground/universal-translator/pull/2/files#diff-20fe4fd4d29fb8bbfe77b061edd8c805R143
I would like to fix this but i'm not really sure what G is stand for. is it like AD and BE(Buddhist Era )?

### CODE REVIEW

**Comment by joeybloggs** [comment]
Thanks for the pull request!

I'll review sometime today, just out with the family now.

as for G, I'll have to dig into that some more; where exactly did you see the "G"?

**Comment by prideloki** [comment]
in here https://github.com/go-playground/universal-translator/blob/master/cmd/resources/data/rules/th.yaml#L60

unlike in the en version, i don't see any G in the date format
https://github.com/go-playground/universal-translator/blob/master/cmd/resources/data/rules/en.yaml#L22

**Comment by joeybloggs** [comment]
Thanks I'll investigate further, maybe just an error/typo but will do some research to make sure; I don't know how Thai date is supposed to be output, that's why I need some help :)

**Comment by prideloki** [comment]
i will help :) 
well,it's not a typo
in Thai full date, we have an era word before the year number because we do use both AD and BE.
so from the format `EEEE\u0E17\u0E35\u0E48 d MMMM G y`, the full date (both in AD and BE) would be
วันจันทร์ที่ 2 มกราคม ค.ศ. 2016 (Monday 2 January AD 2016)
วันจันทร์ที่ 2 มกราคม พ.ศ. 2559 (Monday 2 January BE 2559)

i'm thinking of adding the eras(AD,BE) to the th.yml so the 'G' could be replace by them.
would that be okay?

**Comment by joeybloggs** [comment]
Yes that would be OK.

And thanks! This is very y very helpful :thumbsup:

**Comment by joeybloggs** [comment]
Thanksfor all your help,  I'll have to look at adding the era logic,  just realised I hadn't finished it yet.

It may take me a little while before I can add it, but I'll get it in there.

**Comment by joeybloggs** [comment]
so got a little more research done into this and it looks like the CLDR data contains the era information and I'll extract it from there instead of the plural rules. I apologize for taking so long, just have a few projects and my time is spread pretty thin.

```xml
<eras>
					<eraNames>
						<era type="0">ปีก่อนคริสต์ศักราช</era>
						<era type="0" alt="variant">ก่อนสามัญศักราช</era>
						<era type="1">คริสต์ศักราช</era>
						<era type="1" alt="variant">สามัญศักราช</era>
					</eraNames>
					<eraAbbr>
						<era type="0">ปีก่อน ค.ศ.</era>
						<era type="0" alt="variant">ก.ส.ศ.</era>
						<era type="1">ค.ศ.</era>
						<era type="1" alt="variant">ส.ศ.</era>
					</eraAbbr>
					<eraNarrow>
						<era type="0">ก่อน ค.ศ.</era>
						<era type="0" alt="variant" draft="contributed">ก.ส.ศ.</era>
						<era type="1">ค.ศ.</era>
						<era type="1" alt="variant" draft="contributed">ส.ศ.</era>
					</eraNarrow>
				</eras>
```

**Comment by prideloki** [comment]
no worries, should i remove the latest commit then? the one with the eras in `th.yaml`

**Comment by joeybloggs** [comment]
yes that would be great.

**Comment by joeybloggs** [comment]
Hey @prideloki 

I've added the logic to parse the CLDR Era data and added the logic and pushed it in branch add-era-logic; could you merge that branch into yours and check that it is working? I did add the tests to parse a data with a negative year, but I can't read Thai so...

**Comment by prideloki** [comment]
sure! will do :)

**Comment by prideloki** [comment]
Hi,
i have updated my test cases  here in https://github.com/prideloki/universal-translator/commit/a31ba1a740ac5b67c603b1e9d8bf0795d692bf45
for negative year(BC), the year comes before the era name.
also the era name in full date,right now, is using the era in abbreviation(<eraAbbr><era type="0">ปีก่อน ค.ศ.</era>...) format not the full one(<eras><eraNames><era type="0">ปีก่อนคริสต์ศักราช</era>)
thank you very much for implementing this feature right away after this PR :)

**Comment by joeybloggs** [comment]
No Thanks you for all your help, I will definitely add the printing of the full name in the full date instead of abbrev sometime tonight.


I was wondering if you could help with one more small thing:

are you sure that Era comes after year? This may not be right but the CLDR data shows that Era comes before year, where G is the Era:
```xml
<dateFormats>
					<dateFormatLength type="full">
						<dateFormat>
							<pattern>EEEEที่ d MMMM G y</pattern>
						</dateFormat>
					</dateFormatLength>
					<dateFormatLength type="long">
						<dateFormat>
							<pattern>d MMMM G y</pattern>
						</dateFormat>
					</dateFormatLength>
					<dateFormatLength type="medium">
						<dateFormat>
							<pattern>d MMM y</pattern>
						</dateFormat>
					</dateFormatLength>
					<dateFormatLength type="short">
						<dateFormat>
							<pattern>d/M/yy</pattern>
						</dateFormat>
					</dateFormatLength>
				</dateFormats>
```

Google Translate ( I know not 100% reliable ) translates it to the same text regardless if it's placed before or after.

I rely heavily on the CLDR information, otherwise I would not have the time to maintain this package for every language.

**Comment by prideloki** [comment]
yes, it's a specific case only if the year is negative(i.e. 300BC) otherwise it comes before the year. 
that's what make sense to the native.
i know it would be hard to maintain if there is such a special case.

**Comment by joeybloggs** [comment]
Ok I'm going to have to change translators backend structure a little bit to handle both BC and AD for all date formats like I split up Era. I will copy the AD information to the BC for all languages and then implement a cross-reference override table  to override BC values during locale info generation.

This way I can handle any other exceptions that come up. I kind of needed to do this anyways for the English language to display BC but only for years less than 0 as G isn't in it's datetime format.

It will take me a few more days but I'll try and get it done ASAP

**Comment by joeybloggs** [comment]
Hey @prideloki sorry to bother you again, was working on this and had a question

in Thai the medium date "d MMM y" and Short Date "d/M/yy" should these denote the Era AD or BC... or are they assumed AD in which case I should display era only when it is BC?

**Comment by prideloki** [comment]
yes, medium and short date, the era is assumed to be AD.
For BC, the era is only displayed in full and long date.

**Comment by prideloki** [comment]
@joeybloggs could you share me the link to the `th` xml pls?
so far, i found this link http://unicode.org/repos/cldr/trunk/common/bcp47/calendar.xml
thank you.

**Comment by joeybloggs** [comment]
Thanks @prideloki 

here is the link [th.xml](http://unicode.org/repos/cldr/trunk/common/main/th.xml)

you could also download the CLDR data using this link [CLDR Core](http://unicode.org/Public/cldr/29/core.zip)

extract/unzip it on disk and it is in the following folder "core/common/main/th.xml"

**Comment by joeybloggs** [comment]
Hey @prideloki 

I've updated my code + tests to fix the AD vs BC Date's and DateTime's, if you could please verify that it is correct that would be awesome 👍 

still have to add test for English, but can do that after I know Thai is working correctly.

P.S. Thanks you so much for all your help, I could not make this package better without help from people like yourself! 😃

**Comment by prideloki** [comment]
Hi @joeybloggs , i have corrected the era logic in e94cdad and tested on my repo, all good :)
screen shot 2559-05-07 at 1 09 35 pm
Thanks you as well for being actively updated this repo
this is my very first PR to the open source project, it was a great experience :)

**Comment by joeybloggs** [comment]
Thanks @prideloki had them backwords,may the rest of your open source work go as good :)

**Pull request merged**
